{% set name = "fastscapelib" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fastscape-lem/fastscapelib/archive/v{{ version }}.tar.gz
  sha256: 21cac72a0586d1ceb1080eadbb60a7b7e81a4d6a7b56edbc696f92ff87fc6566

build:
  number: 3

outputs:
  - name: fastscapelib
    script: install_cpp_headers.sh  # [unix]
    script: install_cpp_headers.bat  # [win]
    build:
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - make  # [unix]
      host:
        - xtensor >=0.24,<0.26
      run:
        - xtensor >=0.24,<0.26
    test:
      commands:
        - test -f ${PREFIX}/include/fastscapelib/grid/raster_grid.hpp  # [unix]
        - test -f ${PREFIX}/include/fastscapelib/flow/flow_graph.hpp  # [unix]
        - test -f ${PREFIX}/include/fastscapelib/version.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfigVersion.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\fastscapelib\grid\raster_grid.hpp (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\include\fastscapelib\flow\flow_graph.hpp (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\include\fastscapelib\version.hpp (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\fastscapelibConfig.cmake (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\fastscapelibConfigVersion.cmake (exit 0) else (exit 1)  # [win]
  - name: fastscapelib-python
    build:
      script:
        # C++17 features marked as not available
        # https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
        - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
        - python -m pip install . --no-deps -v --no-build-isolation
      activate_in_script: true
      skip: true  # [python_impl == 'pypy']
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - make  # [unix]
      host:
        - python
        - scikit-build-core >=0.5,<0.11
        - pip
        - numpy
        - pybind11
        - pybind11-abi
        - xtensor-python >=0.27,<0.28
      run:
        - python
    test:
      source_files:
        - python/fastscapelib/tests
      requires:
        - pytest
      imports:
        - fastscapelib
      commands:
        - pytest

about:
  home: https://github.com/fastscape-lem/fastscapelib
  doc_url: https://fastscapelib.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'A C++/Python library of efficient algorithms for landscape evolution modeling'
  description: |
    Fastscapelib is a C++/Python library of efficient and reusable algorithms for
    landscape evolution modeling. It aims at providing a (bare bones) toolkit for
    building your own Landscape Evolution Models (LEMs) or integrating it
    with other existing codes or models.

extra:
  recipe-maintainers:
    - benbovy
