{% set name = "fastscapelib" %}
{% set version = "0.1.3" %}
{% set sha256 = "5872275778af0e02490b33f4bec9d9fe3edbc501d89845ce769ef85b3f463944" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fastscape-lem/fastscapelib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win and vc<14]

outputs:
  - name: fastscapelib
    script: install_cpp_headers.sh   # [unix]
    script: install_cpp_headers.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
      host:
        - xtensor >=0.18.2,<0.19
      run:
        - xtensor >=0.18.2,<0.19
    test:
      commands:
        - test -f ${PREFIX}/include/fastscapelib/fastscapelib.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfigVersion.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\fastscapelib\fastscapelib.hpp (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\fastscapelibConfig.cmake (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\fastscapelibConfigVersion.cmake (exit 0) else (exit 1)  # [win]
  - name: fastscapelib-python
    script: install_python.sh   # [unix]
    script: install_python.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
      host:
        - python
        - setuptools
        - numpy
        - xtensor >=0.18.2,<0.20
        - xtensor-python >=0.21,<0.23
      run:
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - fastscapelib

about:
  home: https://github.com/fastscape-lem/fastscapelib
  doc_url: https://fastscapelib.readthedocs.io
  license: GPLv3
  license_file: LICENSE
  summary: 'Library for topographic analysis and modeling'
  description: |
    Fastscapelib is a C++ library that implements efficient algorithms
    for processing topographic data and landscape evolution
    modeling. It also has Python bindings.

extra:
  recipe-maintainers:
    - benbovy
