{% set name = "fastscapelib" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fastscape-lem/fastscapelib/archive/v{{ version }}.tar.gz
  sha256: 4029657425908b3fc4ef41339bd9db564b0308a4874316c2fdb4c67696db26d9

build:
  number: 0
  skip: True  # [python_impl == 'pypy']

outputs:
  - name: fastscapelib
    script: install_cpp_headers.sh   # [unix]
    script: install_cpp_headers.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [linux]
      host:
        - xtensor >=0.24,<0.25
      run:
        - xtensor >=0.24,<0.25
    test:
      commands:
        - test -f ${PREFIX}/include/fastscapelib/flow_graph.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfigVersion.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\fastscapelib\flow_graph.hpp (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\fastscapelibConfig.cmake (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\fastscapelibConfigVersion.cmake (exit 0) else (exit 1)  # [win]
  - name: fastscapelib-python
    build:
      script: python -m pip install . --no-deps -v --ignore-installed --no-cache-dir --no-build-isolation
      script_env:
        # C++17 features marked not available
        # https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
        - CPPFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY  # [osx]
      activate_in_script: True
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [linux]
      host:
        - python
        - scikit-build-core >=0.5,<0.6
        - pip
        - numpy
        - xtensor-python >=0.26.1,<0.27
      run:
        - python
        - {{ pin_compatible('numpy') }}
    test:
      source_files:
        - python/fastscapelib/tests
      requires:
        - pytest
      imports:
        - fastscapelib
      commands:
        - pytest

about:
  home: https://github.com/fastscape-lem/fastscapelib
  doc_url: https://fastscapelib.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'A C++/Python library of efficient algorithms for landscape evolution modeling'
  description: |
    Fastscapelib is a C++/Python library of efficient and reusable algorithms for
    landscape evolution modeling. It aims at providing a (bare bones) toolkit for
    building your own Landscape Evolution Models (LEMs) or integrating it
    with other existing codes or models.

extra:
  recipe-maintainers:
    - benbovy
