appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fKPdwvw+oyvB4YcQgi6/vLid3u2mjFEl42+iuDtPvkf5YMGoRDbx6vC/ai7BavL6Y94nK9Z3V4HS63+edtC0XsOKMrXqMOXK1FBMofreFnYS1Fa+mJSNQJmNBcJtLjyiy2OHj/nLGZoRTSwObRKAjhEPKgdPE5Q8QAUBw4gUT5srufv2U3rC8RZShFng7mqFuC9bdnn0jcs1pc0Fk5WJp/nM+/BIyYUJ8zXhXuKQp6iyR67Kfb7flZVu2eRbh32jxDGbi087V9DvB72Nn5tdUrd/oeHyZ90NAjehtRwwFjwcmdfRE9QEWlXEC6JZsEzKOPWSfhEIBLCoLqEZehz0/803ffsQP+yHpGnqKg1Ezl5cuWEArp1ObX67Nr3IeTt4DKJF1dWY1gPqTiU0jpOaQzxP6RaK3m5nosQQ0DDuoEAvSweITkSXpyJus2j/Jbyb2Q2AI8FmnMAh9FAsd/lFfrPJ6aDE4Ozot7h+TFc08F7WVTcm8V0uYdD7SvkqfuTf5Ix+V7feqXBw2fA4HaOVPwAFa6G8sDPvsT91tw70TpltDzdMfDzsL2tP4hOQZSqV5T5itmwdcQJ50AKOLfOEJVbaelzfmSzIvO3Qhlbi+xm8hsHJ2CG/dLmGtblr7SoUZ45A9Wu/o5MDrweepLbybbAD5aRZAmu1Wa6nrQk3LjM=}
